spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.85.130
  session:
    store-type: redis
server:
  port: 12000